Repository vexra/css, pull requests merged in 2024-07, with the labels that each got.

#3 Create Basic DB
  prisma/schema.prisma
Labels: enhancement, database

#5 rev the schema
  prisma/schema.prisma
Labels: enhancement, database

#10 add `AccountHolderName` to each registration table
  prisma/schema.prisma
Labels: enhancement, database, registration

#8 form cpc
  .env.example
  package.json
  pnpm-lock.yaml
  prisma/schema.prisma
  src/actions/cpc.ts
  src/app/registrasi-cpc/page.tsx
  src/components/CPCRegistrationForm.tsx
  src/schemas/index.ts
  tailwind.config.ts
Labels: enhancement, javascript, registration

#9 form lct
  src/actions/lct.ts
  src/app/registrasi-lct/page.tsx
  src/components/LCTRegistrationForm.tsx
  src/schemas/index.ts
Labels: enhancement, javascript, registration

#6 Form ml
  pnpm-lock.yaml
  src/actions/ml.ts
  src/app/registrasi-ml/page.tsx
  src/components/LCTRegistrationForm.tsx
  src/components/MLRegistrationForm.tsx
  src/schemas/index.ts
Labels: enhancement, javascript, registration

#7 Form futsal
  src/actions/cpc.ts
  src/actions/futsal.ts
  src/actions/lct.ts
  src/actions/ml.ts
  src/app/registrasi-futsal/page.tsx
  src/components/FutsalRegistrationForm.tsx
  src/schemas/index.ts
Labels: enhancement, javascript, registration

#13 Create Navbar and Footer
  package.json
  pnpm-lock.yaml
  public/images/logo/himakom.png
  src/actions/login.ts
  src/actions/logout.ts
  src/app/(public)/layout.tsx
  src/app/(public)/page.tsx
  src/app/globals.css
  src/components/public/footer.tsx
  src/components/public/navbar.tsx
  src/components/public/navlink.tsx
  src/constants/index.ts
  tailwind.config.ts
Labels: enhancement, javascript

#12 Mobile Legend Description Page
  src/app/(public)/ml/page.tsx
  src/routes.ts
  tailwind.config.ts
Labels: enhancement, javascript

#14 create futsal desc page
  src/app/(public)/futsal/page.tsx
  src/routes.ts
Labels: enhancement, javascript

#15 fix the format check in gh worklfow
  .github/workflows/dev.yml
  pnpm-lock.yaml
  src/app/(public)/futsal/page.tsx
  src/app/(public)/ml/page.tsx
  src/components/public/footer.tsx
Labels: github_actions

#16 Create CPC Description Page and it to public route
  src/app/(public)/cpc/page.tsx
  src/routes.ts
Labels: enhancement, javascript

#17 create LCT description page
  src/app/(public)/lct/page.tsx
  src/routes.ts
Labels: enhancement, javascript

#19 Login page
  src/app/(auth)/login/page.tsx
  src/middleware.ts
  src/routes.ts
Labels: enhancement, javascript

#20 Update registration table
  prisma/schema.prisma
Labels: enhancement, database

#21 create codeql workflow
  .github/workflows/codeql.yml
Labels: enhancement, github_actions

#22 update script
  package.json
Labels: enhancement

#24 fix: add default login page
  src/auth.config.ts
Labels: bug, javascript

#25 add status field to each registration table
  prisma/schema.prisma
Labels: enhancement, database

#26 change color theme
  src/app/(public)/cpc/page.tsx
  src/app/(public)/futsal/page.tsx
  src/app/(public)/lct/page.tsx
  src/app/(public)/ml/page.tsx
Labels: enhancement, javascript

#27 Create Pengumuman Lomba Page
  src/app/(public)/pengumuman-lomba/page.tsx
  src/routes.ts
Labels: enhancement, javascript

#28 Fix middleware wrong redirect
  src/middleware.ts
  src/routes.ts
Labels: bug, javascript

#23 basic homepage
  src/app/(public)/page.tsx
  src/components/public/navbar.tsx
  tailwind.config.ts
Labels: enhancement, javascript

#29 Remove bazar from navbar
  src/app/(public)/layout.tsx
  src/components/public/navbar.tsx
Labels: enhancement, javascript

#30 style: update homepage
  src/app/(public)/page.tsx
Labels: enhancement, javascript

#31 style: update description page
  src/app/(public)/cpc/page.tsx
  src/app/(public)/futsal/page.tsx
  src/app/(public)/lct/page.tsx
  src/app/(public)/ml/page.tsx
  src/app/(public)/page.tsx
Labels: enhancement

#32 style: animation sponsor & medpart
  src/app/(public)/page.tsx
  tailwind.config.ts
Labels: enhancement

#36 Add sponsor logos
  public/images/logo/HIMATIKA.PNG
  public/images/logo/Himatro.png
  public/images/logo/Khazzanah Tour & Travel Cab. Lampung.png
  public/images/logo/LOGO PRO 2 BDL FULL - WIDE CONFIGURATION - SEMENTARA.png
  public/images/logo/LOGO TEKNOKRA.png
  public/images/logo/Logo Himafi-1.png
  public/images/logo/Logo Kawal Event.jpg
  public/images/logo/Logo Kejar Mimpi Lampung.jpg
  public/images/logo/Logo Rakanila.png
  public/images/logo/Logo-seputar.infoid.jpg
  public/images/logo/Olimpiade Update.png
  public/images/logo/PT. EPRAS JAYA MURNI PERKASA.jpeg
  public/images/logo/infolomba.PNG
  public/images/logo/logo hima IF.png
  public/images/logo/logo mpl.png
  public/images/logo/logolombasma2.png
  public/images/logo/pikr unila.jpeg
  src/app/(public)/cpc/page.tsx
  src/app/(public)/page.tsx
Labels: enhancement
