Repository vexra/css, pull requests merged in 2024-09, with the labels that each got.

#44 fix forgotten `institution` field
  src/components/FutsalRegistrationForm.tsx
Labels: bug, javascript

#49 Modified date
  src/app/(public)/cpc/page.tsx
  src/app/(public)/futsal/page.tsx
  src/app/(public)/lct/page.tsx
  src/app/(public)/ml/page.tsx
  src/app/registrasi-futsal/page.tsx
Labels: enhancement, javascript

#50 add github acc in readme
  README.md
Labels: documentation

#51 Datetm
  src/app/(public)/cpc/page.tsx
  src/app/(public)/futsal/page.tsx
  src/app/(public)/lct/page.tsx
  src/app/(public)/ml/page.tsx
  src/app/registrasi-ml/page.tsx
Labels: enhancement, javascript
